default: &default
  secret_key_base: "656113c96430dec7831a5c114d6e179594a412a355a319635425a3f6dd12e496b4a8f439e41668271317a245844aa885a14f8ae7a8c4d7b7ddc685f5782b2950"
  billing_service_api_key: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiaWxsaW5nIiwiaWF0IjoxNzQzMDg1NDk5LCJleHAiOm51bGwsImF1ZCI6Ind3dy5leGFtcGxlLmNvbSIsInN1YiI6ImJpbGxpbmdfY2xpZW50In0.aRwnR_QP6AlOv_JanMkbhwe9ACDcJc5184pXdR0ksXg"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"
  billing_service_api_key: "<%= ENV["SUBSCRIPTION_API_KEY"] %>"